config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  namespace :admin do
    resource :purveyor, controller: 'purveyor', only: [:edit, :update]
    resources :ftp_profiles do 
      get 'current', on: :member
    end

    get 'filling_consumers',  to: 'filling_consumers#set_params'
    post 'filling_consumers', to: 'filling_consumers#start'

    get 'filling_consumptions',  to: 'filling_consumptions#set_params'
    post 'filling_consumptions', to: 'filling_consumptions#start'

    get 'filling_distributions',  to: 'filling_distributions#set_params'
    post 'filling_distributions', to: 'filling_distributions#start'

    get 'filling_ccertificates',  to: 'filling_ccertificates#set_params'
    post 'filling_ccertificates',  to: 'filling_ccertificates#start'

    get 'filling_dcertificates', to: 'filling_dcertificates#set_params'
    post 'filling_dcertificates', to: 'filling_dcertificates#start'
  end

  resources :consumers do
    resources :payments
    resources :eic_codes
    resources :consumptions do
      post 'selector', on: :collection
    end
    resources :distributions do
      post 'selector', on: :collection
    end
    get 'client_changed', to: 'consumers#client_changed'
    get 'purveyor', to: 'admin/purveyor#show'
    get 'annual_consumptions', to: 'annual_consumptions#show'
    get 'sources', to: 'sources#index'
    get 'commercial_information', to: 'commercial_information#index'
  end

  resources :users
  
  root to: 'consumers#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new

    if user.admin_role?
        can :manage, :all
    end

    if user.manager_role?
        can :manage, Consumer
        can :manage, Consumption
        can :manage, Distribution
        can :manage, Payment
        can :manage, EicCode
        can :read, Purveyor
        can [:new, :create, :index], User
        can :show, :annual_consumption
        can :index, :commercial_information
        can :index, :source
    end

    if user.client_role?
        can [:read, :edit, :update], Consumer
        can [:index, :show, :selector], Consumption
        can [:index, :show, :selector], Distribution
        can :read, Payment
        can :read, EicCode
        can :read, Purveyor
        can :show, :annual_consumption
        can :index, :commercial_information
        can :index, :source
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ccertificate.rb
class Ccertificate < ApplicationRecord
	has_one_attached :print_form, dependent: :destroy
end

app/models/consumer.rb
class Consumer < ApplicationRecord
	has_many :payments, dependent: :destroy
	has_many :eic_codes, dependent: :destroy
	has_many :consumptions, dependent: :destroy
	has_many :distributions, dependent: :destroy
end

app/models/consumption.rb
class Consumption < ApplicationRecord
  belongs_to :consumer
  has_one :ccertificate, dependent: :destroy

  def text_period
    "#{UA_MONTHS_SINGLE[self.period.month]} #{self.period.year}"
  end

  def year
    self.period.year
  end
end

app/models/dcertificate.rb
class Dcertificate < ApplicationRecord
	has_one_attached :print_form, dependent: :destroy
end

app/models/distribution.rb
class Distribution < ApplicationRecord
  belongs_to :consumer
  has_one :dcertificate, dependent: :destroy

   def text_period
    "#{UA_MONTHS_SINGLE[self.period.month]} #{self.period.year}"
  end
end

app/models/eic_code.rb
class EicCode < ApplicationRecord
end

app/models/ftp_profile.rb
class FtpProfile < ApplicationRecord
  validates :host,      presence: true
  validates :port,      presence: true
  validates :username,  presence: true
  validates :password,  presence: true

  def dec_password
    if self.password == nil
      return nil
    else
      return EncryptionService.decrypt(self.password) 
    end
  end

  def dec_password=(value)
    self.password = EncryptionService.encrypt(value)
  end
    
  def set_current
    FtpProfile.update_all(default: false)
    self.default = true
    self.save
  end

  def self.get_current
    FtpProfile.find_by(default: true)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :consumer

  def textualize
    "До #{self.date} числа #{UA_PERIOD_FULL[self.period]}"
  end
end

app/models/purveyor.rb
class Purveyor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/annual_consumptions_controller.rb
class AnnualConsumptionsController < ApplicationController
  include Verifiable

  before_action :set_consumer
  before_action :detect_invalid_user
  authorize_resource :class => false

  def show
  	e_scope = @consumer.consumptions
    d_scope = @consumer.distributions
    @years = GetUniqueYearsQuery.call(e_scope)
    @current_year = params['year'] || @years.first
    if @current_year
    	@annual_e_consumption = GetAnnualConsumptionsQuery.call(e_scope, @current_year)
      @annual_e_cost = GetAnnualCostQuery.call(e_scope, @current_year)
      @annual_d_cost = GetAnnualCostQuery.call(d_scope, @current_year)
    end
    Rails.logger.control.debug("Consumer Annual #{@consumer.name} : Index : #{current_user.name}")
  end

  private

  def set_consumer
    @consumer = Consumer.find(params[:consumer_id])
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  include Verifiable
  before_action :set_consumer
  before_action :detect_invalid_user
  authorize_resource :class => false

  def index
  end
  
  private
  
  def set_consumer
    @consumer = Consumer.find(params[:consumer_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:update, :destroy, :edit]
  load_and_authorize_resource

  def index
    @users = User.order(:name)
  end

  def destroy
    if (@user.admin_role?) && (User.where(admin_role: true).count <= 1)
      flash[:alert] = 'Неможливо видалити останнього адміністратора'
    else
      @user.destroy ? flash[:notice] = 'Користувач був успішно видалений' : flash[:alert] = 'Неможливо видалити цього користувача'
    end
    redirect_to users_path
  end

  def edit
  end

  def update
    if (@user.admin_role?) && (User.where(admin_role: true).count <= 1) && (user_params[:admin_role] == "0")
      flash[:alert] = 'Неможливо видалити останнього адміністратора'
      redirect_to users_path
    else
      if @user.update(user_params)
        flash[:notice] = "Користувач #{@user.name} був успішно відредагований" 
        redirect_to users_path
      else
        flash[:alert] = 'Неможливо відредагувати користувача'
        render :edit
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:admin_role, :manager_role, :client_role, :name, :email)
  end
end

app/helpers/annual_consumptions_helper.rb
module AnnualConsumptionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/consumptions_helper.rb
module ConsumptionsHelper
end

app/helpers/distributions_helper.rb
module DistributionsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/annual_consumptions/_chart.html.erb
<br>
<div class='row'>
	<div class='col'>
		<%= column_chart chart_data, ytitle: y_title, dataset: { backgroundColor: '#deebf7', borderColor: '#348fd2', borderWidth: 1 } %>
	</div>
</div>
<br />
<div class='row'>
	<div class='col-md-12'>
		<div class="table-responsive">
			<table class='table table-sm table-bordered'>
				<thead class='thead-light'>
					<tr>
						<th class='text-center'>Розрахунковий місяць</th>
						<% chart_data.each do |item| %>
							<th class='text-center align-middle small'> <%= item[0] %> </th>
						<% end %>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td class='text-center'><%= table_title %></td>
						<% chart_data.each do |item| %>
							<td class='text-center align-middle'> <%= number_with_precision(item[1], precision: precision) %> </td>
						<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/annual_consumptions/show.html.erb
<div class='row'>
	<div class='col-md-3'></div>
	<div class='col-md-9'><h3><%= @consumer.name %></h3></div>
</div>

<div class='row'>
	<div class='col-md-3'>
		<%= render '/buttons', active: 6 %>
	</div>
	
	<div class='col-md-9 border-orange border rounded py-2 mb-2'>
		<% if @years.first %>
			<div class='row'>
				<div class='col-md-12'>
					<%= form_tag consumer_annual_consumptions_path(@consumer), method: 'get' do %>
						<div class="form-row align-items-end">
							<div class="col-auto">
								<%= label_tag 'year', 'Розрахунковий рік:' %>
							</div>
							<div class="col-auto">
								<%= select_tag 'year', options_for_select(@years, @current_year), class: 'form-control' %>
							</div>
							<div class='col-auto'>
								<%= button_tag 'Показати', class: 'btn3d btn btn-primary mb-1' %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
			<br />

			<ul class="nav nav-tabs" id="myTab" role="tablist">
			  <li class="nav-item">
			    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#econsumption">Обсяги споживання електроенергії</a>
			  </li>
			  <li class="nav-item">
			    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#ecost">Вартість споживання електроенергії</a>
			  </li>
			  <% if @consumer.distribution %>
				  <li class="nav-item">
				    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#dcost">Вартість послуги з розподілу</a>
				  </li>
				<% end %>
			</ul>
			<div class="tab-content" id="myTabContent">
			  <div class="tab-pane fade show active" id="econsumption">
			  	<%= render 'chart', chart_data: @annual_e_consumption, y_title: 'МВт*год', table_title: 'Фактично спожитий обсяг е/е, МВт*год.', precision: 3 %>
			  </div>
			  <div class="tab-pane fade" id="ecost">
			  	<%= render 'chart', chart_data: @annual_e_cost, y_title: 'грн.', table_title: 'Вартість споживання е/е, грн. з ПДВ', precision: 2 %>
			  </div>
			  <% if @consumer.distribution %>
			  	<div class="tab-pane fade" id="dcost">
			  		<%= render 'chart', chart_data: @annual_d_cost, y_title: 'грн.', table_title: 'Вартість послуги з розподілу е/е, грн. з ПДВ', precision: 2 %>
			  	</div>
			  <% end %>	
			</div>
		<% else %>
			<br />
			<p class="font-italic text-danger text-center">Відомості про споживання електроенергії відсутні</p>
		<% end %>
	</div>
</div>

<div class='row'>
	<div class='col-md-3'>
	</div>

	<div class='col-md-3'>
		<%= link_to consumers_path, class: "btn3d text-white btn btn-warning btn-block" do %>
			<i class="fas fa-undo-alt"></i> Повернутись
		<% end %>
	</div>

</div>