config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  namespace :admin do
    resource :purveyor, controller: 'purveyor', only: [:edit, :update]
    resources :ftp_profiles do 
      get 'current', on: :member
    end

    get 'filling_consumers',  to: 'filling_consumers#set_params'
    post 'filling_consumers', to: 'filling_consumers#start'

    get 'filling_consumptions',  to: 'filling_consumptions#set_params'
    post 'filling_consumptions', to: 'filling_consumptions#start'

    get 'filling_distributions',  to: 'filling_distributions#set_params'
    post 'filling_distributions', to: 'filling_distributions#start'

    get 'filling_ccertificates',  to: 'filling_ccertificates#set_params'
    post 'filling_ccertificates',  to: 'filling_ccertificates#start'

    get 'filling_dcertificates', to: 'filling_dcertificates#set_params'
    post 'filling_dcertificates', to: 'filling_dcertificates#start'
  end

  resources :consumers do
    resources :payments
    resources :eic_codes
    resources :consumptions do
      post 'selector', on: :collection
    end
    resources :distributions do
      post 'selector', on: :collection
    end
    get 'client_changed', to: 'consumers#client_changed'
    get 'purveyor', to: 'admin/purveyor#show'
    get 'annual_consumptions', to: 'annual_consumptions#show'
    get 'sources', to: 'sources#index'
    get 'commercial_information', to: 'commercial_information#index'
  end

  resources :users
  
  root to: 'consumers#index'
end

app/models/ftp_profile.rb
class FtpProfile < ApplicationRecord
  validates :host,      presence: true
  validates :port,      presence: true
  validates :username,  presence: true
  validates :password,  presence: true

  def dec_password
    if self.password == nil
      return nil
    else
      return EncryptionService.decrypt(self.password) 
    end
  end

  def dec_password=(value)
    self.password = EncryptionService.encrypt(value)
  end
    
  def set_current
    FtpProfile.update_all(default: false)
    self.default = true
    self.save
  end

  def self.get_current
    FtpProfile.find_by(default: true)
  end
end

app/controllers/admin/ftp_profiles_controller.rb
class Admin::FtpProfilesController < ApplicationController
  before_action :set_ftp_profile, only: [:edit, :update, :destroy, :curent]
  load_and_authorize_resource

  def index
    @ip = request.remote_ip
    @ftp_profiles = FtpProfile.order(:name, :host, :port)
  end

  def new
    @ftp_profile = FtpProfile.new
  end

  def current
    @ftp_profile.set_current
    redirect_to admin_ftp_profiles_path
  end

  def create
    @ftp_profile = FtpProfile.new(ftp_profile_params)
    if @ftp_profile.save
      redirect_to admin_ftp_profiles_path, notice: "Профіль #{@ftp_profile.name} успішно створений"
    else
      flash[:alert] = 'Неможливо створити профіль'
      render :new
    end
  end

  def edit
  end

  def update
    if @ftp_profile.update(ftp_profile_params)
      redirect_to admin_ftp_profiles_path, notice: "Профіль #{@ftp_profile.name} успішно відредагований"
    else
      flash[:alert] = 'Неможливо відредагувати профіль'
      render :edit
    end
  end

  def destroy
    if @ftp_profile.destroy
      flash[:notice] = "Профіль #{@ftp_profile.name} успішно видалений"
    else
      flash[:alert] = 'Неможливо видалити профіль'
    end
    redirect_to admin_ftp_profiles_path
  end

  private

  def ftp_profile_params
    params.require(:ftp_profile).permit(:host, :port, :username, :password,
                                        :default, :name, :dec_password)
  end

  def set_ftp_profile
    @ftp_profile = FtpProfile.find(params[:id])
  end
end

app/helpers/admin/ftp_profiles_helper.rb
module Admin::FtpProfilesHelper
end

app/views/admin/ftp_profiles/_form.html.erb
<%= form_for [:admin, ftp_profile] do |f| %>

	<div class="form-group row">
		<%= f.label :name, "Найменування", class: "col-md-2 col-form-label" %>
		<div class="col-md-10">
			<%= f.text_field :name, class: "form-control" %>
		</div>
	</div>
		
	<div class="form-group row">
		<%= f.label :host,"Хост", class: "col-md-2 col-form-label" %>
		<div class="col-md-7">
			<%= f.text_field :host, class: "form-control" %>
				<div class="invalid-feedback">повинен бути присутнім</div>
		</div>
		<%= f.label :port,"Порт", class: "col-md-1 col-form-label" %>
		<div class="col-md-2">
			<%= f.number_field :port, class: "form-control" %>
				<div class="invalid-feedback">повинен бути присутнім</div>
		</div>
	</div>

	<div class="form-group row">
		<%= f.label :username,"Користувач", class: "col-md-2 col-form-label" %>
		<div class="col-md-5">
			<%= f.text_field :username, class: "form-control" %>
				<div class="invalid-feedback">повинен бути присутнім</div>
		</div>
		<%= f.label :dec_password,"Пароль", class: "col-md-1 col-form-label" %>
		<div class="col-md-4">
			<%= f.password_field :dec_password, class: "form-control", value: ftp_profile.dec_password %>
				<div class="invalid-feedback">повинен бути присутнім</div>
		</div>
	</div>

	<%= f.hidden_field :default %>

	<div class="row">
		<div class="col-md-3">
			<%= f.button type: 'submit', class: "btn3d btn btn-primary btn-block" do %>
				<i class="fas fa-save"></i> Зберегти
			<% end %>
		</div>
		<div class="col-md-3">
			<%= link_to :back, class: "text-white btn3d btn btn-warning btn-block" do %>
				<i class="fas fa-undo-alt"></i> Повернутись
			<% end %>
		</div>
	</div>
<% end %>

app/views/admin/ftp_profiles/edit.html.erb
<h3>Редагування профілю <%= @ftp_profile.name %></h3>
<p>
<%= render 'form', ftp_profile: @ftp_profile %>
</p>

app/views/admin/ftp_profiles/index.html.erb
<h3>Профілі FTP з'єднання</h3>

<p>
<%= link_to new_admin_ftp_profile_path, class: "btn3d btn btn-primary" do %>
	<i class="fas fa-plus"></i> Створити новий профіль FTP
<% end %>
</p>
<p>
	<table class="table table-striped table-sm">
		<thead>
			<tr>
				<th>#</th>
				<th>Найменування</th>
				<th>Хост</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% n = 0 %>
			<% @ftp_profiles.each do |profile| %>
				<tr>
					<td><%= n+=1 %></td>
					<td><%= profile.name %></td>
					<td><%= "#{profile.host}:#{profile.port}" %></td>
					<td class="text-center">
						<% if profile.default %>
							<span class="btn btn-primary btn-sm"> Поточній </span>
						<% else %>
							<%= link_to 'Зробити поточним', current_admin_ftp_profile_path(profile), class: "btn btn-outline-primary btn-sm" %>
						<% end %>
					</td>
					<td class="text-center">
						<div class="btn-group">
							<%= link_to edit_admin_ftp_profile_path(profile), 
								class: "btn btn-outline-dark btn-sm" do %>
								<i class="fas fa-edit test-edit-payment"></i>
							<% end %>
							<%= link_to [:admin, profile], method: :delete, 
								class: "btn btn-outline-danger btn-sm",
								data: {confirm: "Ви впевнені що хочете видалити профіль #{profile.name}?"} do %>
								<i class="fas fa-times test-delete-payment">&nbsp;</i>
							<% end %>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</p>

app/views/admin/ftp_profiles/new.html.erb
<h3>Новий профіль</h3>
<p>
<%= render 'form', ftp_profile: @ftp_profile %>
</p>