config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  namespace :admin do
    resource :purveyor, controller: 'purveyor', only: [:edit, :update]
    resources :ftp_profiles do 
      get 'current', on: :member
    end

    get 'filling_consumers',  to: 'filling_consumers#set_params'
    post 'filling_consumers', to: 'filling_consumers#start'

    get 'filling_consumptions',  to: 'filling_consumptions#set_params'
    post 'filling_consumptions', to: 'filling_consumptions#start'

    get 'filling_distributions',  to: 'filling_distributions#set_params'
    post 'filling_distributions', to: 'filling_distributions#start'

    get 'filling_ccertificates',  to: 'filling_ccertificates#set_params'
    post 'filling_ccertificates',  to: 'filling_ccertificates#start'

    get 'filling_dcertificates', to: 'filling_dcertificates#set_params'
    post 'filling_dcertificates', to: 'filling_dcertificates#start'
  end

  resources :consumers do
    resources :payments
    resources :eic_codes
    resources :consumptions do
      post 'selector', on: :collection
    end
    resources :distributions do
      post 'selector', on: :collection
    end
    get 'client_changed', to: 'consumers#client_changed'
    get 'purveyor', to: 'admin/purveyor#show'
    get 'annual_consumptions', to: 'annual_consumptions#show'
    get 'sources', to: 'sources#index'
    get 'commercial_information', to: 'commercial_information#index'
  end

  resources :users
  
  root to: 'consumers#index'
end

app/models/consumption.rb
class Consumption < ApplicationRecord
  belongs_to :consumer
  has_one :ccertificate, dependent: :destroy

  def text_period
    "#{UA_MONTHS_SINGLE[self.period.month]} #{self.period.year}"
  end

  def year
    self.period.year
  end
end

app/controllers/consumptions_controller.rb
class ConsumptionsController < ApplicationController
  include Verifiable
  
  before_action :set_consumer
  before_action :detect_invalid_user
  load_and_authorize_resource

  def index
    @consumptions = @consumer.consumptions.all.order(period: :desc)
    @consumption = @consumptions.first
    redirect_to consumer_consumption_path(@consumer, @consumption) if @consumption
    Rails.logger.control.debug("Consumer Consumption #{@consumer.name} : Index : #{current_user.name}")
  end

  def show
     @consumptions = @consumer.consumptions.all.order(period: :desc)
     @consumption = Consumption.find(params[:id])
     Rails.logger.control.debug("Consumer Consumption #{@consumer.name} : Show : #{current_user.name}")
  end

  def selector
    @consumption = Consumption.find(params[:consumption_id])
    redirect_to consumer_consumption_path(@consumer, @consumption)
  end

  private

  def set_consumer
    @consumer = Consumer.find(params[:consumer_id])
  end

end

app/helpers/consumptions_helper.rb
module ConsumptionsHelper
end

app/views/consumptions/index.html.erb
<div class='row'>
	<div class='col-md-3'></div>
	<div class='col-md-9'><h3><%= @consumer.name %></h3></div>
</div>

<div class='row'>
	<div class='col-md-3'>
		<%= render '/buttons', active: 4 %>
	</div>
	<div class='col-md-9 border-orange border rounded py-2 mb-2'>
		<br />
		<p class="font-italic text-danger text-center">Відомості про розрахунки за електроенергію відсутні</p>
	</div>
</div>

<div class='row'>
	<div class='col-md-3'>
	</div>

	<div class='col-md-3'>
		<%= link_to consumers_path, class: "btn3d text-white btn btn-warning btn-block" do %>
			<i class="fas fa-undo-alt"></i> Повернутись
		<% end %>
	</div>

</div>

app/views/consumptions/show.html.erb
<div class='row'>
	<div class='col-md-3'></div>
	<div class='col-md-9'><h3><%= @consumer.name %></h3></div>
</div>

<div class='row'>
	<div class='col-md-3'>
		<%= render '/buttons', active: 4 %>
	</div>
	<div class='col-md-9 border-orange border rounded py-2 mb-2'>

		<%= form_tag selector_consumer_consumptions_path(@consumer) do %>
			<div class="form-row align-items-end">
				<div class="col-auto">
					<%= label_tag 'consumption_id', 'Розрахунковий період:' %>
				</div>
				<div class="col-auto">
					<%= select_tag 'consumption_id', options_from_collection_for_select(@consumptions, :id, :text_period, @consumption.id), class: 'form-control' %>
				</div>
				<div class='col-auto'>
					<%= button_tag 'Показати', class: 'btn3d mb-1 btn btn-primary' %>
				</div>
			</div>
		<% end %>
		<br />
		<div class='row my-2'>
			<div class='col-md-5 text-right'> Вхідне сальдо: </div>
			<div class="col-md-2 border rounded text-center <%= @consumption.opening_balance < 0 ? 'text-danger' : '' %>"> <%= number_with_precision(@consumption.opening_balance, precision:2, delimiter: ' ') %> </div> 
			<div class='col-md-5'> грн., в т.ч. ПДВ 20% </div>
		</div>
		<div class='row my-2'>
			<div class='col-md-5 text-right'> Сплачені грошові кошти: </div>
			<div class="col-md-2 border rounded text-center"> <%= number_with_precision(@consumption.money, precision:2, delimiter: ' ') %> </div> 
			<div class='col-md-5'> грн., в т.ч. ПДВ 20% </div>
		</div>
		<div class='row my-2'>
			<div class='col-md-5 text-right'> Нараховано за спожиту електроенергію: </div>
			<div class="col-md-2 border rounded text-center"> <%= number_with_precision(@consumption.cost, precision:2, delimiter: ' ') %> </div> 
			<div class='col-md-5'> грн., в т.ч. ПДВ 20% </div>
		</div>
		<div class='row my-2'>
		<div class='col-md-5 text-right'> Вихідне сальдо: </div>
			<div class="col-md-2 border rounded text-center <%= @consumption.closing_balance < 0 ? 'text-danger' : '' %>"> <%= number_with_precision(@consumption.closing_balance, precision:2, delimiter: ' ') %> </div> 
			<div class='col-md-5'> грн., в т.ч. ПДВ 20% </div>
		</div>

		<br/>

		<div class='row'>
			<p class='col text-center'>Акти прийому-передачі електроенергії</p>
		</div>
		<div class='row' >
			<div class='col' >
				<div class='table-responsive table-vertical'>
					<table class="table table-striped table-bordered table-sm">
						<thead class="thead-light">
							<tr>
								<th class='text-center'>Номер документу</th>
								<th class='text-center'>Дата документу</th>
								<th class='text-center'>Сума грн., в т.ч. ПДВ 20%</th>
								<th class='text-center'>Розрахунковий період</th>
								<th class='text-center'>Завантажити</th>
							</tr>
						</thead>
						<tbody>
							<% @consumptions.each do |consumption| %>
								<% @certificate = consumption.ccertificate %>
								<% if @certificate %>
									<tr>
										<td class='text-center'><%= @certificate.number %></td>
										<td class='text-center'><%= consumption.period %></td>
										<td class='text-right'><%= number_with_precision(consumption.cost, precision:2, delimiter: ' ') %></td>
										<td class='text-center'><%= consumption.text_period %></td>
										<td class='text-center'>
											<%= link_to rails_blob_path(@certificate.print_form, disposition: "attachment"), class: "btn btn-outline-danger" do %>
    												<i class="fas fa-file-pdf"></i>
  											<% end %>
										</td>
									</tr>
								<% end %>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<div class='row'>
	<div class='col-md-3'>
	</div>

	<div class='col-md-3'>
		<%= link_to consumers_path, class: "btn3d text-white btn btn-warning btn-block" do %>
			<i class="fas fa-undo-alt"></i> Повернутись
		<% end %>
	</div>

</div>